//! The Swift and Kotlin heads check themselves against the surface manifest
//! (decision 0090). Both are generated by UniFFI from this crate's
//! exports, so this test reads the exported functions from the source (the
//! `pub fn`s inside `#[uniffi::export]` blocks and the exported free
//! functions) and compares them with the manifest's `swift` and `kotlin`
//! columns in both directions; CI separately greps the generated bindings
//! themselves (tooling/check-surface-bindings.sh), so the camel-case names
//! here are checked against what ships, not only inferred.

use std::collections::BTreeSet;
use std::path::Path;

fn snake(camel: &str) -> String {
    let mut out = String::new();
    for c in camel.chars() {
        if c.is_ascii_uppercase() {
            out.push('_');
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// The functions UniFFI exports, as `Object.method` for a method or
/// constructor in an `impl` block under `#[uniffi::export]`, and a bare name
/// for an exported free function.
fn exported_fns(source: &str) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    let mut armed = false;
    let mut object: Option<String> = None;
    let mut depth = 0i32;
    for line in source.lines() {
        let t = line.trim_start();
        if t.starts_with("#[uniffi::export") {
            armed = true;
            continue;
        }
        if armed && t.starts_with("impl ") {
            object = t
                .strip_prefix("impl ")
                .map(|r| r.trim_end_matches(" {").trim().to_owned());
            depth = 0;
            armed = false;
        }
        let fn_name = t
            .strip_prefix("pub async fn ")
            .or_else(|| t.strip_prefix("pub fn "))
            .map(|r| {
                r.chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect::<String>()
            });
        if armed {
            if let Some(name) = fn_name.clone() {
                names.insert(name);
                armed = false;
            } else if !t.starts_with('#') && !t.starts_with("//") && !t.is_empty() {
                armed = false;
            }
        }
        if let Some(obj) = &object {
            if depth == 1
                && let Some(name) = fn_name
            {
                names.insert(format!("{obj}.{name}"));
            }
            depth += line.matches('{').count() as i32;
            depth -= line.matches('}').count() as i32;
            if depth <= 0 && line.contains('}') {
                object = None;
            }
        }
    }
    names
}

#[test]
fn the_ffi_exports_and_the_manifest_agree_both_ways() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let manifest: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(root.join("../../sdk/surface.json")).expect("manifest"),
    )
    .expect("sdk/surface.json parses");
    let exports = exported_fns(&std::fs::read_to_string(root.join("src/lib.rs")).expect("lib.rs"));
    assert!(!exports.is_empty(), "found no uniffi exports");

    let mut named = BTreeSet::new();
    let mut missing = Vec::new();
    for object in manifest["objects"].as_array().expect("objects") {
        for call in object["calls"].as_array().expect("calls") {
            for head in ["swift", "kotlin"] {
                let Some(symbol) = call[head].as_str() else {
                    continue;
                };
                // `Tenant.signIn` names a method on that object; `signUpTls`
                // names a free function. Each is checked where it lives.
                let name = match symbol.split_once('.') {
                    Some((object, method)) => format!("{object}.{}", snake(method)),
                    None => snake(symbol),
                };
                named.insert(name.clone());
                if !exports.contains(&name) {
                    missing.push(format!("{head}: {symbol}"));
                }
            }
        }
    }
    assert!(
        !named.is_empty(),
        "the manifest names no Swift or Kotlin symbols"
    );
    assert!(
        missing.is_empty(),
        "sdk/surface.json names symbols tacenta-ffi does not export: {missing:?}"
    );

    let unlisted = &manifest["unlisted"]["ffi"];
    let unrecorded: Vec<&String> = exports
        .iter()
        .filter(|e| !named.contains(*e) && unlisted.get(e.as_str()).is_none())
        .collect();
    assert!(
        unrecorded.is_empty(),
        "exports that are neither a row of sdk/surface.json nor listed under unlisted.ffi: {unrecorded:?}"
    );
}

#[test]
fn the_ffi_error_cases_and_the_manifest_agree_both_ways() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let manifest: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(root.join("../../sdk/surface.json")).expect("manifest"),
    )
    .expect("sdk/surface.json parses");
    let source = std::fs::read_to_string(root.join("src/lib.rs")).expect("lib.rs");
    // The variants of `pub enum ClientError`, by brace depth.
    let mut cases = BTreeSet::new();
    let mut inside = false;
    let mut depth = 0i32;
    for line in source.lines() {
        let t = line.trim_start();
        if !inside && t.starts_with("pub enum ClientError ") {
            inside = true;
            depth = 0;
        }
        if inside {
            // A comment or attribute line neither names a case nor counts
            // toward the braces: a doc comment may quote one.
            if t.starts_with("//") || t.starts_with('#') || t.is_empty() {
                continue;
            }
            if depth == 1 {
                let v: String = t
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect();
                if !v.is_empty() {
                    cases.insert(v);
                }
            }
            depth += line.matches('{').count() as i32;
            depth -= line.matches('}').count() as i32;
            if depth <= 0 && line.contains('}') {
                break;
            }
        }
    }
    assert!(!cases.is_empty(), "found no ClientError cases");
    for (head, prefix) in [("swift", "ClientError."), ("kotlin", "ClientException.")] {
        let named: BTreeSet<String> = manifest["errors"]["kinds"]
            .as_array()
            .expect("errors.kinds")
            .iter()
            .filter_map(|k| k[head].as_str())
            .map(|symbol| {
                symbol
                    .strip_prefix(prefix)
                    .unwrap_or_else(|| panic!("{head} error symbols start with {prefix}"))
                    .to_owned()
            })
            .collect();
        assert_eq!(
            named, cases,
            "{head}: sdk/surface.json's error kinds and ClientError's cases differ"
        );
    }
}
