//! Snapshot and restore for the directory, mirroring the relay's
//! (decision record 0016): serialize the registered material to bytes a
//! caller can persist, and rebuild through the ordinary `register` API so
//! a reloaded directory satisfies the same trust-on-first-use binding as a
//! live one — nothing bypasses it.
//!
//! Only the entries are serialized; the per-user device index is
//! regenerated by `register` on restore. Entries are emitted in a
//! deterministic order so snapshots are diffable.

use crate::Directory;
use crate::protocol::{put_addr, put_bytes, put_u32, take_addr, take_bytes, take_u32};
use tacenta_relay::DeviceAddr;

/// The current snapshot format version: entries, recovery keys, and the
/// witnessed persisted-state generations (decision 0078).
///
/// v2 carries the one-time-bundle pool. v3 adds the generations section. Both
/// are read: a v2 `directory.snapshot` must still load, or restart would be
/// fatal (a corrupt snapshot stops startup). A v2 snapshot restores with no
/// witnessed generations, which is correct — the anchor simply starts fresh.
const SNAPSHOT_VERSION: u8 = 0x03;

/// The previous version, still accepted on restore.
const SNAPSHOT_VERSION_V2: u8 = 0x02;

impl Directory {
    /// Serialize every registered device — its address, identity key, and
    /// prekey bundle — to bytes a caller can persist.
    pub fn snapshot(&self) -> Vec<u8> {
        let mut devices: Vec<&DeviceAddr> = self.entries.keys().collect();
        devices.sort_by(|a, b| a.user.cmp(&b.user).then(a.device.cmp(&b.device)));

        let mut out = Vec::new();
        out.push(SNAPSHOT_VERSION);
        put_u32(
            &mut out,
            u32::try_from(devices.len()).expect("entry count fits u32"),
        );
        for device in devices {
            let entry = &self.entries[device];
            put_addr(&mut out, device);
            put_bytes(&mut out, &entry.identity);
            put_bytes(&mut out, &entry.bundle);
            // The pool must survive a restart. A directory that forgets which
            // one-time bundles it has already dispensed serves them again,
            // which is exactly what decision 0074 rules out -- arriving by a
            // process restart rather than by a concurrent lookup.
            put_u32(
                &mut out,
                u32::try_from(entry.pool.len()).expect("pool depth fits u32"),
            );
            for pooled in &entry.pool {
                put_bytes(&mut out, pooled);
            }
        }

        // Recovery keys, in a deterministic order, in their own section.
        let mut recoveries: Vec<&DeviceAddr> = self.recovery.keys().collect();
        recoveries.sort_by(|a, b| a.user.cmp(&b.user).then(a.device.cmp(&b.device)));
        put_u32(
            &mut out,
            u32::try_from(recoveries.len()).expect("recovery count fits u32"),
        );
        for device in recoveries {
            put_addr(&mut out, device);
            put_bytes(&mut out, &self.recovery[device]);
        }

        // Witnessed generations, in a deterministic order, in their own section
        // (decision 0078). These must survive a restart: a directory that
        // forgets the highest generation it has seen would accept a rolled-back
        // state after every server restart, which is the very attack 0078
        // closes — reintroduced by a restart rather than a file rewrite.
        let mut gens: Vec<&DeviceAddr> = self.generations.keys().collect();
        gens.sort_by(|a, b| a.user.cmp(&b.user).then(a.device.cmp(&b.device)));
        put_u32(
            &mut out,
            u32::try_from(gens.len()).expect("generation count fits u32"),
        );
        for device in gens {
            put_addr(&mut out, device);
            out.extend_from_slice(&self.generations[device].to_be_bytes());
        }
        out
    }

    /// Reconstruct a directory from a [`Directory::snapshot`]. `None` if the
    /// bytes are malformed. Each entry is replayed through `register`, so
    /// the reconstructed directory carries the same address-to-identity
    /// bindings; a snapshot has one entry per address, so every replay is a
    /// fresh `Registered`.
    pub fn restore(bytes: &[u8]) -> Option<Directory> {
        let (&version, rest) = bytes.split_first()?;
        // v2 (no generations section) and v3 (with it) are both accepted; a
        // running server's snapshot is v2 and must still load.
        if version != SNAPSHOT_VERSION && version != SNAPSHOT_VERSION_V2 {
            return None;
        }
        let has_generations = version == SNAPSHOT_VERSION;
        let (count, mut rest) = take_u32(rest)?;
        let mut directory = Directory::new();
        for _ in 0..count {
            let (device, r) = take_addr(rest)?;
            let (identity, r) = take_bytes(r)?;
            let (bundle, r) = take_bytes(r)?;
            let (pool_len, mut r) = take_u32(r)?;
            directory.register(&device, identity.to_vec(), bundle.to_vec());
            let mut pool = Vec::with_capacity(pool_len as usize);
            for _ in 0..pool_len {
                let (pooled, next) = take_bytes(r)?;
                pool.push(pooled.to_vec());
                r = next;
            }
            if !pool.is_empty() {
                // `register` above cleared the pool, as a fresh registration
                // must; put back what was actually left undispensed.
                directory.deposit_prekeys(&device, identity, pool);
            }
            rest = r;
        }
        let (rec_count, mut rest) = take_u32(rest)?;
        for _ in 0..rec_count {
            let (device, r) = take_addr(rest)?;
            let (key, r) = take_bytes(r)?;
            rest = r;
            // The entry was restored above, so `set_recovery` binds it.
            directory.set_recovery(&device, key.to_vec());
        }

        // The generations section exists only in v3. A v2 snapshot ends after
        // recovery; its generations start empty, which is correct.
        if has_generations {
            let (gen_count, mut r) = take_u32(rest)?;
            for _ in 0..gen_count {
                let (device, next) = take_addr(r)?;
                let (gen_bytes, next) = next.split_at_checked(8)?;
                let generation = u64::from_be_bytes(gen_bytes.try_into().ok()?);
                directory.restore_generation(&device, generation);
                r = next;
            }
            rest = r;
        }
        rest.is_empty().then_some(directory)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Witness;

    /// Witnessed generations survive a restart, and an old snapshot without them
    /// still loads.
    #[test]
    fn witnessed_generations_survive_a_restart() {
        let bob = DeviceAddr::new("+bob", 1);
        let alice = DeviceAddr::new("+alice", 1);
        let mut dir = Directory::new();
        dir.register(&bob, b"bob-id".to_vec(), b"b-bundle".to_vec());
        dir.register(&alice, b"alice-id".to_vec(), b"a-bundle".to_vec());
        assert_eq!(dir.witness(&bob, 12), Witness::Fresh);
        // Alice registered but never witnessed: no anchor to persist.

        let snapshot = dir.snapshot();
        assert_eq!(
            snapshot[0], SNAPSHOT_VERSION,
            "written in the current format"
        );
        let mut restored = Directory::restore(&snapshot).expect("v3 snapshot restores");

        // The anchor survived: a rollback is still caught after the restart.
        assert_eq!(restored.generation(&bob), Some(12));
        assert_eq!(restored.witness(&bob, 5), Witness::RolledBack);
        // Alice starts fresh, having never been witnessed.
        assert_eq!(restored.generation(&alice), None);
        assert_eq!(restored.witness(&alice, 1), Witness::Fresh);
    }

    /// A pre-0078 snapshot (v2, no generations section) still restores — the
    /// format on a running server — with the anchor simply starting empty. A
    /// break here would stop the server booting, since a corrupt snapshot is
    /// fatal at startup.
    #[test]
    fn a_v2_snapshot_without_generations_still_restores() {
        // Minimal v2 snapshot: version 0x02, zero entries, zero recovery keys,
        // and NO generations section at all.
        let mut v2 = Vec::new();
        v2.push(SNAPSHOT_VERSION_V2);
        put_u32(&mut v2, 0); // entries
        put_u32(&mut v2, 0); // recovery keys

        let mut dir = Directory::restore(&v2).expect("a v2 snapshot restores");
        // No generations were carried; the anchor is fresh, and a newly
        // registered device witnesses normally.
        let bob = DeviceAddr::new("+bob", 1);
        dir.register(&bob, b"bob-id".to_vec(), b"bundle".to_vec());
        assert_eq!(dir.witness(&bob, 3), Witness::Fresh);
    }

    /// A restart must not re-serve what was already dispensed.
    ///
    /// Without the pool in the snapshot, a process restart would reset the
    /// pool to whatever `register` replayed -- empty -- or to the full batch.
    /// Either way the directory would forget which one-time bundles are spent,
    /// which is what decision 0074 rules out, arriving by restart instead of
    /// by concurrency.
    #[test]
    fn the_undispensed_pool_survives_a_restart() {
        let bob = DeviceAddr::new("+bob", 1);
        let mut dir = Directory::new();
        dir.register(&bob, b"bob-id".to_vec(), b"fallback".to_vec());
        dir.deposit_prekeys(
            &bob,
            b"bob-id",
            vec![b"otp-1".to_vec(), b"otp-2".to_vec(), b"otp-3".to_vec()],
        );

        // Two are spent before the restart.
        assert_eq!(dir.take_bundle(&bob), Some(b"otp-1".to_vec()));
        assert_eq!(dir.take_bundle(&bob), Some(b"otp-2".to_vec()));

        let snapshot = dir.snapshot();
        drop(dir);
        let mut dir = Directory::restore(&snapshot).expect("snapshot restores");

        assert_eq!(dir.pool_depth(&bob), 1, "the spent bundles came back");
        assert_eq!(dir.take_bundle(&bob), Some(b"otp-3".to_vec()));
        assert_eq!(dir.take_bundle(&bob), Some(b"fallback".to_vec()));
    }

    /// An unknown snapshot version is refused rather than misparsed. There was
    /// no version byte at all until the pool needed a place in the format.
    #[test]
    fn an_unknown_snapshot_version_is_refused() {
        let bob = DeviceAddr::new("+bob", 1);
        let mut dir = Directory::new();
        dir.register(&bob, b"bob-id".to_vec(), b"bundle".to_vec());
        let mut snapshot = dir.snapshot();
        snapshot[0] = 0x01;
        assert!(Directory::restore(&snapshot).is_none());
    }

    #[test]
    fn survives_a_restart() {
        let bob1 = DeviceAddr::new("+bob", 1);
        let bob2 = DeviceAddr::new("+bob", 2);
        let alice = DeviceAddr::new("+alice", 1);

        let mut dir = Directory::new();
        dir.register(&bob1, b"bob1-id".to_vec(), b"bob1-bundle".to_vec());
        dir.register(&bob2, b"bob2-id".to_vec(), b"bob2-bundle".to_vec());
        dir.register(&alice, b"alice-id".to_vec(), b"alice-bundle".to_vec());

        // Persist, drop, reload — as a server restart would.
        let snapshot = dir.snapshot();
        drop(dir);
        let mut dir = Directory::restore(&snapshot).expect("snapshot restores");

        // Material and the device index survived exactly.
        assert_eq!(dir.identity(&bob1), Some(&b"bob1-id"[..]));
        assert_eq!(dir.bundle(&bob2), Some(&b"bob2-bundle"[..]));
        assert_eq!(
            dir.lookup(&alice),
            Some((b"alice-id".to_vec(), b"alice-bundle".to_vec()))
        );
        assert_eq!(dir.devices_of("+bob"), &[1, 2]);
        assert_eq!(dir.devices_of("+alice"), &[1]);
    }

    #[test]
    fn recovery_keys_survive_a_restart() {
        let bob = DeviceAddr::new("+bob", 1);
        let mut dir = Directory::new();
        dir.register(&bob, b"bob-id".to_vec(), b"bob-bundle".to_vec());
        dir.set_recovery(&bob, b"bob-recovery".to_vec());

        let dir = Directory::restore(&dir.snapshot()).expect("snapshot restores");
        assert_eq!(dir.recovery_key(&bob), Some(&b"bob-recovery"[..]));
        // A device with no recovery key stays without one.
        assert_eq!(dir.recovery_key(&DeviceAddr::new("+bob", 2)), None);
    }

    #[test]
    fn empty_round_trips_and_junk_is_rejected() {
        let snapshot = Directory::new().snapshot();
        assert_eq!(
            Directory::restore(&snapshot).unwrap().devices_of("+x"),
            &[] as &[u32]
        );
        assert!(Directory::restore(&[0xff]).is_none());
        assert!(Directory::restore(&[]).is_none());
    }

    #[test]
    fn a_restored_directory_still_binds_on_first_use() {
        let bob = DeviceAddr::new("+bob", 1);
        let mut dir = Directory::new();
        dir.register(&bob, b"bob-id".to_vec(), b"bob-bundle".to_vec());
        let dir = Directory::restore(&dir.snapshot()).unwrap();

        // The binding is intact after restore: a different identity for the
        // same address is still rejected.
        let mut dir = dir;
        assert_eq!(
            dir.register(&bob, b"other-id".to_vec(), b"other-bundle".to_vec()),
            crate::Registration::Rejected
        );
    }
}
